// <auto-generated />
using Jira_2._0.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jira_2._0.Migrations
{
    [DbContext(typeof(JiraDBContext))]
    partial class JiraDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jira_2._0.Models.AssignedIssues", b =>
                {
                    b.Property<int>("IssueID")
                        .HasColumnType("int");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("AssignedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IssueID", "ProjectID");

                    b.HasIndex("ProjectID");

                    b.ToTable("AssignedIssues");
                });

            modelBuilder.Entity("Jira_2._0.Models.IssueModelWrapper", b =>
                {
                    b.Property<int>("IssueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IssueID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IssueID"));

                    b.Property<string>("IssueData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data");

                    b.HasKey("IssueID");

                    b.ToTable("Issues", (string)null);
                });

            modelBuilder.Entity("Jira_2._0.Models.ProjectModelWrapper", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<string>("ProjectData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data");

                    b.HasKey("ProjectID");

                    b.ToTable("ProjectsData", (string)null);
                });

            modelBuilder.Entity("Jira_2._0.Models.ResolvedIssues", b =>
                {
                    b.Property<int>("IssueID")
                        .HasColumnType("int");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("ResolvedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IssueID", "ProjectID");

                    b.HasIndex("ProjectID");

                    b.ToTable("ResolvedIssues");
                });

            modelBuilder.Entity("Jira_2._0.Models.AssignedIssues", b =>
                {
                    b.HasOne("Jira_2._0.Models.IssueModelWrapper", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jira_2._0.Models.ProjectModelWrapper", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Jira_2._0.Models.ResolvedIssues", b =>
                {
                    b.HasOne("Jira_2._0.Models.IssueModelWrapper", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jira_2._0.Models.ProjectModelWrapper", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
